[phases.setup]
nixPkgs = ["python311", "gcc", "git"]

[phases.install]
cmds = [
    "python3.11 -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[start]
cmd = "python bot.py"
